# ==========================================================
# AKMAL NETWORK
# MELOLO CUMULATIVE ADDRESS LIST
# Generated by DNS3
# DO NOT EDIT MANUALLY
# ==========================================================

/ip firewall address-list
add list=MELOLO address=199.232.114.73 comment="p19-novel-sign-sg.fizzopic.org AS54113"
add list=MELOLO address=103.124.139.72 comment="v16-ml.melolostatic.com AS138089"
add list=MELOLO address=103.124.139.74 comment="v16-ml.melolostatic.com AS138089"
add list=MELOLO address=140.248.130.13 comment="v19-ml.melolostatic.com AS54113"
add list=MELOLO address=23.221.50.105 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.221.50.106 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.221.50.107 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.221.50.112 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.221.50.113 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.221.50.114 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.221.50.115 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.221.50.98 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.221.50.99 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=140.248.130.73 comment="p19-vodimg-default-sign.ibyteimg.com AS54113"
add list=MELOLO address=184.87.193.137 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=184.87.193.139 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=184.87.193.140 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=184.87.193.141 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=184.87.193.147 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=184.87.193.148 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=184.87.193.149 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=184.87.193.150 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=184.87.193.151 comment="v16-ml.melolostatic.com AS20940"
