# ==========================================================
# AKMAL NETWORK
# MELOLO AUTO ADDRESS LIST
# Generated by DNS3
# DO NOT EDIT MANUALLY
# ==========================================================

/ip firewall address-list
add list=MELOLO address=140.248.130.73 comment="p19-novel-sign-sg.fizzopic.org AS54113"
add list=MELOLO address=199.232.114.73 comment="p19-novel-sign.fizzopic.org AS54113"
add list=MELOLO address=146.75.46.73 comment="p19-vodimg-default-sign.ibyteimg.com AS54113"
add list=MELOLO address=23.215.35.146 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.215.35.155 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.215.35.157 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.215.35.159 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.215.35.160 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.215.35.161 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.215.35.162 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.215.35.163 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=23.215.35.165 comment="v16-ml.melolostatic.com AS20940"
add list=MELOLO address=199.232.114.13 comment="v19-ml.melolostatic.com AS54113"
